### ISSUE TITLE
[Help] can someone help me make a batch for the new update  please and thank you

### ISSUE THREAD

**Issue by DragonVsKira** [izu-co/funimation-downloader-nx#7] opened 2021-06-27 18:30 UTC
** Main info: **

Script version: 4.8.2
Show ID: My Hero Academia
Episode ID: 01

** Additional Info: **
every time i try within  a batch i get this .....**it work fin in cmd** so im lost ps Script version: 4.8.1 batch  work fin but not 4.8.2
my batch code 

@echo off

"C:\Users\Dvk\Videos\funimation-downloader-nx-4.8.2-win64\funi.exe" -s 124389 -e 1  --fileName "${showTitle} - S${season}E${episode} - ${title} - [${height}p] [FuniDub][DVK]"

timeout 30

sorry if this is not a bug i need it helps do u have a discord to look 4 help 

=== Funimation Downloader NX 4.8.2 ===

[INFO] Selected Episodes: 0001

[INFO] My Hero Academia - S1E1 - Izuku Midoriya: Origin
[INFO] Available streams (Non-Encrypted):
[#1245946] Spanish (Latin Am) [Uncut]  (defaulted to English subtitles)
[#787532] Japanese [Uncut]
[#293823] English [Uncut] (selected)
[#124392] Japanese [Simulcast]
[#131848] English [Simulcast]  (defaulted to English subtitles)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (534KiB/s)
         2: 480x270 (769KiB/s)
         3: 640x360 (1006KiB/s)
         4: 640x360 (1723KiB/s)
         5: 960x540 (2348KiB/s)
         6: 1280x720 (2964KiB/s)
         7: 1280x720 (4296KiB/s)
         8: 1440x810 (6042KiB/s)
         9: 1920x1080 (7931KiB/s)
        10: 1920x1080 (9670KiB/s)
[INFO] Selected layer: 7 (1280x720) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/1605008/English/1605008_English_7491080_a777aba2-32ee-e611-80c5-0017a4776c06_Layer7.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8xNjA1MDA4L0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyNDgxNjc4Mn19fV19&Signature=uhQOVoQUKWxU8kAj4FlN~x7x3O48v5MQaXubsxyQ95277fPUCsThQH~Z0GEBt0tGjvRopQFci8qgNBX3WKNnJ26D3T6iHJp8FG47cNDZN5wWdEB0qP73aGYlPVUhsd5un04JIwdELqDiJw6EzANJttX7UXSjs1TZ6OMGItmLoH53P2ogkad3lWmlg4L7nKoQq4ohQOYbE3jYz05WC0lbwwZJeNPJX0WlUlFunTp1vAWplf7ZY5eqiA7LfCmcwrkpyvpu9G-ZOoXERSFwkK0gcjKITwG3wQJvbVdxXf56t28zwyYgbgIYOzLDcGt6AGLfdGMvYi9koirZtZY5pGFGqQ__&rt=1478555
[INFO] Output filename: My Hero Academia - S01E01 - Izuku Midoriya_ Origin - [720p] [FuniDub][DVK].ts
**(node:9672) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined**
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:375:7)
    at downloadStreams (C:\snapshot\funimation-downloader-nx\funi.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getEpisode (C:\snapshot\funimation-downloader-nx\funi.js)
    at async getShow (C:\snapshot\funimation-downloader-nx\funi.js)
(Use `funi --trace-warnings ...` to show where the warning was created)
(node:9672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by izu-co** [comment] 2021-06-27 18:32
Investigating

**Comment by izu-co** [comment] 2021-06-27 18:47
Alright, so it seems that you are using PowerShell. In that case, just try changing the ```"``` sounding the filename to ```'``` like so:
```"C:\Users\Dvk\Videos\funimation-downloader-nx-4.8.2-win64\funi.exe" -s 124389 -e 1 --fileName '${showTitle} - S${season}E${episode} - ${title} - [${height}p] [FuniDub][DVK]'```.

In a normal cmd, the version with the ```"``` should work. 
I am going to close this issue. If this did not help you, feel free to reopen this issue with the output from the changed command.

**Comment by DragonVsKira** [comment] 2021-06-28 16:35
here a video 
https://drive.google.com/file/d/1U_hAZv1ciACqiDlhTmN0hukaEzYMfHpC/view?usp=sharing

of what im taking about

**Comment by DragonVsKira** [comment] 2021-06-28 16:53
i do not no how to reopen this issue im new to github

**Comment by izu-co** [comment] 2021-06-28 16:56
Please note that you are not logged in in the second terminal. Can you log in and retry please?

**Comment by DragonVsKira** [comment] 2021-06-28 17:00
terminal? i only had them  open  did u look at the video ?

**Comment by izu-co** [comment] 2021-06-28 17:01
Yes I did. And the one on the right stated that the token is not set, indicating that you are not logged in.

**Comment by DragonVsKira** [comment] 2021-06-28 17:06
but i did logged in.

**Comment by izu-co** [comment] 2021-06-28 17:07
As long as there is no message saying no token set you are not. Maybe its because you are using the exe in one batch file and the node.js version in the other?

**Comment by DragonVsKira** [comment] 2021-06-28 17:10
it work fin if i cmd cd then  funi.exe -s 1396445 -e 1 -q 7 --mkv --mks

but not the .bat

**Comment by izu-co** [comment] 2021-06-28 17:17
I was able to reproduce the error.
You will hear from me again once I have more information.

**Comment by izu-co** [comment] 2021-06-28 17:34
Fixed with https://github.com/izu-co/funimation-downloader-nx/commit/987f64ee0e80b8e84ba2e0ac47e29710f6059598.
The update can be downloaded from [here](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.8.3).

Please give me an update if this worked for you. If you don't, I will close this issue within one day.

**Comment by DragonVsKira** [comment] 2021-06-28 17:35
ok will do

**Comment by DragonVsKira** [comment] 2021-06-28 17:56
ok so that fix :) thanks you your the man thanks 

but 
if i do not do this i get this 

ffmpeg: C:\funidownloader-nx\funimation-downloader-nx-4.8.3-win64/bin/ffmpeg/ffmpeg.exe
mkvmerge: C:\funidownloader-nx\funimation-downloader-nx-4.8.3-win64/bin/bin/mkvtoolnix/mkvmerge.exe

i get this

[WARN] MKVMerge not found, skip using this...
[WARN] FFmpeg not found, skip using this...

but if it not a easy it all good

**Comment by izu-co** [comment] 2021-06-28 18:01
Hey there.
https://github.com/izu-co/funimation-downloader-nx/commit/6e19808585182b398e463bca27c4442603ce0155 is the fix, so just redownload [this](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.8.3) release.

As always, let me know if that resolve the issue.

**Comment by DragonVsKira** [comment] 2021-06-28 19:05
no :( it all good

**Comment by izu-co** [comment] 2021-06-28 19:05
So it didn’t change anything?

**Comment by DragonVsKira** [comment] 2021-06-28 19:08
MkvMerge 
ffmpeg

only detected  when i put and yes i did redownload it


fmpeg: C:\funidownloader-nx\funimation-downloader-nx-4.8.3-win64/bin/ffmpeg/ffmpeg.exe
mkvmerge: C:\funidownloader-nx\funimation-downloader-nx-4.8.3-win64/bin/bin/mkvtoolnix/mkvmerge.exe

**Comment by izu-co** [comment] 2021-06-28 19:16
[funimation-downloader-nx-4.8.3-win64.zip](https://github.com/izu-co/funimation-downloader-nx/files/6728730/funimation-downloader-nx-4.8.3-win64.zip)
Can you please try the attached file? It contains a special build used to output debug information.
Unzip the zip file in any **new** directory and insert the relative (e.g. ./bin/mkvmerge) path. After making sure its set, please run the program and send me the output.

**Comment by DragonVsKira** [comment] 2021-06-28 19:22
do i run with default setting or add file path to 

MkvMerge
ffmpeg

**Comment by izu-co** [comment] 2021-06-28 19:23
Add the file path. It would be best if you just copy the settings from the funimation downloaded that is configured (copy all settings files and the bin directory)

**Comment by DragonVsKira** [comment] 2021-06-28 19:32
=== Funimation Downloader NX 4.8.3 ===

before {
  ffmpeg: 'C:\\funidownloader-nx\\New folder\\funimation-downloader-nx-4.8.3-win64\\bin\\ffmpeg\\ffmpeg.exe',
  mkvmerge: 'C:\\funidownloader-nx\\New folder\\funimation-downloader-nx-4.8.3-win64\\bin\\mkvtoolnix\\mkvmerge.exe'
}
after {
  ffmpeg: 'C:\\funidownloader-nx\\New folder\\funimation-downloader-nx-4.8.3-win64\\bin\\ffmpeg\\ffmpeg.exe',
  mkvmerge: 'C:\\funidownloader-nx\\New folder\\funimation-downloader-nx-4.8.3-win64\\bin\\mkvtoolnix\\mkvmerge.exe'
}
ffmpeg C:\funidownloader-nx\New folder\funimation-downloader-nx-4.8.3-win64\bin\ffmpeg\ffmpeg.exe
mkvmerge C:\funidownloader-nx\New folder\funimation-downloader-nx-4.8.3-win64\bin\mkvtoolnix\mkvmerge.exe

**Comment by izu-co** [comment] 2021-06-28 19:34
Don’t insert the absolut path please. Do it like ./bin/ffmpeg and then run it from somewhere else using their terminal. 
If you want replace the funi.exe in your current Setup with the one from the zip and then run your batch.

just make sure you use relative paths

**Comment by DragonVsKira** [comment] 2021-06-28 19:37
=== Funimation Downloader NX 4.8.3 ===

before {
  ffmpeg: './bin/ffmpeg/ffmpeg.exe',
  mkvmerge: './bin/mkvtoolnix/mkvmerge.exe'
}
after {
  ffmpeg: 'C:\\funidownloader-nx\\funimation-downloader-nx-4.8.3-win64-debug-information\\bin\\ffmpeg\\ffmpeg.exe',
  mkvmerge: 'C:\\funidownloader-nx\\funimation-downloader-nx-4.8.3-win64-debug-information\\bin\\mkvtoolnix\\mkvmerge.exe'
}
ffmpeg C:\funidownloader-nx\funimation-downloader-nx-4.8.3-win64-debug-information\bin\ffmpeg\ffmpeg.exe
mkvmerge C:\funidownloader-nx\funimation-downloader-nx-4.8.3-win64-debug-information\bin\mkvtoolnix\mkvmerge.exe

**Comment by izu-co** [comment] 2021-06-28 19:38
Looking at this results, the newest version should work.

**Comment by izu-co** [comment] 2021-06-28 19:40
Just in case something went wrong on my side, can you try the newest release again.
I don't see why it shouldn't work as intended.

**Comment by DragonVsKira** [comment] 2021-06-28 19:40
ok ill redl it do

**Comment by DragonVsKira** [comment] 2021-06-28 19:51
video link
https://drive.google.com/file/d/1-WhtKVqLVO1DLlya5CJZ33aQO900S9px/view?usp=sharing

**Comment by izu-co** [comment] 2021-06-28 19:54
Hm, OK, so I would suggest we pull the last resort card. Can you send me your setup (all files, including the bat mkvmerge etc) in a zip file? I will take a look at it and try to pinpoint the issue.

**Comment by DragonVsKira** [comment] 2021-06-28 20:05
https://drive.google.com/file/d/12dDrBPdlbpufnIPtOYqxb0uLbJB2QwXO/view?usp=sharing

i del my token

**Comment by izu-co** [comment] 2021-06-28 20:06
That's a wise thing to do.
It may take me some time to find the error, just in case I won't respond today.

**Comment by DragonVsKira** [comment] 2021-06-28 20:09
u what it funimation-downloader-nx-4.8.3-win64 with  my bat,mkvmerge,ffmpeg right ?

**Comment by izu-co** [comment] 2021-06-28 20:09
Yes

**Comment by izu-co** [comment] 2021-06-28 20:39
Alright, so I just tested it and I didn't make any changes to the current version. It worked without errors.
When I tested it with your version, the tools were indeed not found. Therefore, I have included the latest funi.exe. Just replace the current with the new one, and it should work. 
[funi.zip](https://github.com/izu-co/funimation-downloader-nx/files/6729169/funi.zip)

**Comment by DragonVsKira** [comment] 2021-06-28 21:59
that did it it work 💯  now thanks you 🥇

**Closed** 2021-06-29 05:07 UTC
Labels: bug
